#print("Hello World!")
#print("Hello Again")
#print("I like typing this.")
#print("This is fun.")
#print('Yay! Printing')
#print("I'd much ratheryou 'not'.")
#print('I "said" do not touch this.')
print("This is my personal line.")
